version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}

      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      - FACEBOOK_APP_CALLBACK_URL=${FACEBOOK_APP_CALLBACK_URL}

      - GOOGLE_CLIEN_ID=${GOOGLE_CLIEN_ID}
      - GOOGLE_CLIEN_SECRET=${GOOGLE_CLIEN_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}

      - BUCKET_NAME=${BUCKET_NAME}
      - BUCKET_REGION=${BUCKET_REGION}
      - BUCKET_ACCESS_KEY_ID=${BUCKET_ACCESS_KEY_ID}
      - BUCKET_SECRET_ACCESS_KEY=${BUCKET_SECRET_ACCESS_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - '3306:3306'
